### ISSUE TITLE
IsAlpha & isAlphaNum

### ISSUE THREAD

**Issue by michailVestnik** [dogukanakkaya/deno-validify#1]
Hi!

Please add **isAlpha** and **isAplhaNumeric**! 
I found the solution:
https://github.com/validatorjs/validator.js/blob/master/src/lib/isAlpha.js
https://github.com/validatorjs/validator.js/blob/master/src/lib/isAlphanumeric.js

Спасибо!

**Comment by dogukanakkaya** [comment]
`isAlpha()` and `isAlphanumeric()` functions are added.
